kraken: {
    label: "Kraken"

    scanner: {
        label: "scanner"
    }

    runner: {
        label: "runner/executor/scheduler"
    }

    reporter: {
        label: "reporter"
    }

    abi_modules: {
        label: "ABI Modules (.so/.dll/.dylib)"
    }

    runner <-> abi_modules: "intra process comunication (CABI)"
}

kraken.scanner -> kraken.runner: "Found targets"
kraken.runner -> kraken.reporter: "Results"

external_modules: {
    label: "External Module"
    cli
}

network_modules: {
    label: "Network Module"
    grpc
}

kraken.runner <-> external_modules.cli: "inter process comunication (CLI)"
kraken.runner <-> network_modules.grpc: "inter network comunication (gRPC)" {
    style: {
        stroke-dash: 3
    }
}

targets: {
    label: "Targets"

    target1
    target2
    targetn
}


kraken.runner -> targets.target1: {
    style.stroke-dash: 3
}

kraken.runner -> targets.target2: {
    style.stroke-dash: 3
}

kraken.runner -> targets.targetn: {
    style.stroke-dash: 3
}
