// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64be || armbe || mips || mips64 || mips64p32 || ppc64 || s390 || s390x || sparc || sparc64
// +build arm64be armbe mips mips64 mips64p32 ppc64 s390 s390x sparc sparc64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Do not access this directly. https://github.com/cilium/ebpf/pull/23/files
//
//go:embed bpf_bpfeb.o
var _BpfBytes []byte

// NewBpfObjects loads eBPF objects from an ELF file.
//
// Verifier output:  Read from /sys/kernel/debug/tracing/verifiers/bpf_bpfeb.o
//
// This function is invisible to the user.
func NewBpfObjects() (*BpfObjects, error) {
	obj, err := ebpf.LoadCollection(bytes.NewReader(_BpfBytes))
	if err != nil {
		return nil, err
	}

	var objs BpfObjects
	if err := obj.Assign(&objs); err != nil {
		return nil, err
	}

	return &objs, nil
}

// BpfObjects contains all objects after they have been loaded into the kernel.
type BpfObjects struct {
	XdpProg     *ebpf.Program `ebpf:"xdp_prog"`
	XdpRingbuf *ebpf.Map     `ebpf:"xdp_ringbuf"`
}

// BpfPrograms contains all programs after they have been loaded into the kernel.
type BpfPrograms struct {
	XdpProg *ebpf.Program `ebpf:"xdp_prog"`
}

// BpfMaps contains all maps after they have been loaded into the kernel.
type BpfMaps struct {
	XdpRingbuf *ebpf.Map `ebpf:"xdp_ringbuf"`
}

// LoadBpfObjects loads eBPF objects from an ELF file.
//
// Verifier output:  Read from /sys/kernel/debug/tracing/verifiers/bpf_bpfeb.o
func LoadBpfObjects(obj *BpfObjects, opts *ebpf.CollectionOptions) error {
	return ebpf.LoadAndAssign(obj, bytes.NewReader(_BpfBytes), opts)
}
