FROM ubuntu:resolute AS builder

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y build-essential python3-dev automake cmake git flex bison libglib2.0-dev libpixman-1-dev python3-setuptools cargo libgtk-3-dev wget curl python3-pip cpio libcapstone-dev && \
    apt-get install -y lld-18 llvm-18 llvm-18-dev clang-18 && \
    apt-get install -y gcc-$(gcc --version|head -n1|sed 's/\..*//'|sed 's/.* //')-plugin-dev libstdc++-$(gcc --version|head -n1|sed 's/\..*//'|sed 's/.* //')-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/AFLplusplus/AFLplusplus && \
    cd AFLplusplus && \
    git submodule update --init && \
    make distrib PERFORMANCE=1 NO_PYTHON=1 && \
    make install

FROM ubuntu:resolute

ENV DEBIAN_FRONTEND=noninteractive

COPY --from=builder /usr/local /usr/local

WORKDIR /work
