name: Release

on:
    push:
        tags:
            - "v*.*.*"
    workflow_dispatch:

permissions:
    contents: write

jobs:
    build:
        name: Build and Release
        runs-on: ubuntu-latest
        env:
            GOOS: linux
            GOARCH: amd64
        steps:
            - uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.25.1"

            - name: Install build dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y protobuf-compiler clang
                  sudo snap install just --classic

            - name: Configure kernel headers include path for eBPF
              run: echo "C_INCLUDE_PATH=/usr/include/$(gcc -dumpmachine)" >> $GITHUB_ENV

            - name: Install protobuf generators
              run: |
                  go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
                  go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
                  echo "$HOME/go/bin" >> $GITHUB_PATH

            - name: Build binaries
              run: |
                  just kraken_build
                  just siren_build

            - name: Archive release files
              working-directory: dist
              run: |
                  zip kraken-${{ env.GOOS }}-${{ env.GOARCH }}.zip kraken
                  zip siren-${{ env.GOOS }}-${{ env.GOARCH }}.zip siren
                  zip modules-src.zip -r ../modules

            - name: Create GitHub release
              uses: softprops/action-gh-release@v2
              with:
                  files: dist/*.zip
